### PR TITLE
Mask twice

### LINKED ISSUE #161: mask evaluates raster mask RDD twice
This process graph will evaluate the raster mask RDD twice. This is not a huge problem for file-based collections but in the case of Sentinel Hub, it will do unnecessary tile requests. In particular this sends out a single tile request for the data (N02), and 2 identical tile requests for the mask (CLOUD_FRACTION), for a total of 3.

```json
{
    "process": {
        "process_graph": {
            "aggregate_spatial_SYQWW9649F": {
                "arguments": {
                    "data": {
                        "from_node": "mask_VSQIU8474G"
                    },
                    "geometries": {
                        "features": [
                            {
                                "geometry": {
                                    "coordinates": [
                                        [
                                            [
                                                6.1,
                                                46.16
                                            ],
                                            [
                                                6.11,
                                                46.16
                                            ],
                                            [
                                                6.11,
                                                46.17
                                            ],
                                            [
                                                6.1,
                                                46.17
                                            ],
                                            [
                                                6.1,
                                                46.16
                                            ]
                                        ]
                                    ],
                                    "type": "Polygon"
                                },
                                "properties": {
                                    "anAttribute": 4
                                },
                                "type": "Feature"
                            }
                        ],
                        "name": "file3bfa35c9b0eb",
                        "type": "FeatureCollection"
                    },
                    "reducer": {
                        "process_graph": {
                            "mean_HMBYP8947D": {
                                "arguments": {
                                    "data": {
                                        "from_parameter": "data"
                                    },
                                    "ignore_nodata": true
                                },
                                "process_id": "mean",
                                "result": true
                            }
                        }
                    }
                },
                "process_id": "aggregate_spatial"
            },
            "load_collection_IYGCM4847Z": {
                "arguments": {
                    "bands": [
                        "CLOUD_FRACTION"
                    ],
                    "id": "SENTINEL_5P_L2",
                    "spatial_extent": {
                        "east": 6.11,
                        "north": 46.17,
                        "south": 46.16,
                        "west": 6.1
                    },
                    "temporal_extent": [
                        "2018-07-01",
                        "2018-07-01"
                    ]
                },
                "process_id": "load_collection"
            },
            "load_collection_NQWJY7513T": {
                "arguments": {
                    "bands": [
                        "NO2"
                    ],
                    "id": "SENTINEL_5P_L2",
                    "spatial_extent": {
                        "east": 6.11,
                        "north": 46.17,
                        "south": 46.16,
                        "west": 6.1
                    },
                    "temporal_extent": [
                        "2018-07-01",
                        "2018-07-01"
                    ]
                },
                "process_id": "load_collection"
            },
            "mask_VSQIU8474G": {
                "arguments": {
                    "data": {
                        "from_node": "load_collection_NQWJY7513T"
                    },
                    "mask": {
                        "from_node": "load_collection_IYGCM4847Z"
                    }
                },
                "process_id": "mask"
            },
            "save_result_AJAUF5705Y": {
                "arguments": {
                    "data": {
                        "from_node": "aggregate_spatial_SYQWW9649F"
                    },
                    "format": "GTIFF"
                },
                "process_id": "save_result",
                "result": true
            }
        }
    },
    "job_options": {
        "sentinel-hub": {
            "client-alias": "vito"
        },
        "logging-threshold": "debug",
        "node_caching": true
    }
}
```

Enabling/omitting "node_caching" makes no difference. Strangely, I have also witnessed a batch job that in fact did only 2 requests (1 for the data, 1 for the mask) but that one didn't even specify "node_caching" (defaults to false). :thinking:

### PR DESCRIPTION
**Pull request by EmileSonneveld**

### CODE REVIEW

**Comment by EmileSonneveld** [comment]
Graph to show how `applyDataMask` was moved:
```mermaid
flowchart TD
  tileSourcesToDataCube --> |-| applyDataMask
  tileSourcesToDataCube --> rasterRegionsToTiles
  readMultibandTileLayer_L843 --> rasterRegionsToTiles
  rasterRegionsToTiles --> |+| applyDataMask
  readKeysToRasterSources --> |-| applyDataMask
  readMultibandTileLayer_L843 --> readKeysToRasterSources
  readMultibandTileLayer_L279 --> tileSourcesToDataCube

```

**Comment by jdries** [comment]
Can we add a test for pixel based masking at load time? Otherwise looks good!

**Comment by EmileSonneveld** [comment]
There is a `def multibandWithSpacetimeMask` test that fails when tiles are no longer discarted. I enhanced it by adding a reference image and testing to it.

**Review by jdries — APPROVED** [review]
looks good

**Pull request merged**
