### PR TITLE
Use larger timeout for all Http calls.

### LINKED ISSUE #342: SocketTimeoutException: Read timed out towards SHub Catalog API
The cropsar process graph [mentioned](https://github.com/Open-EO/openeo-geopyspark-driver/issues/279#issuecomment-1429360601) in #279 will still not succeed after the changes in that ticket to avoid SHub batch processes: `java.net.SocketTimeoutException: Read timed out`.

Is this another manifestation of https://github.com/Open-EO/openeo-geotrellis-extensions/issues/93? It looks like there are integration tests that currently suffer from the same problem; is it a transient error or something that we have to fix?

To investigate why this happens.

### PR DESCRIPTION
**Pull request by EmileSonneveld**
https://github.com/Open-EO/openeo-geopyspark-driver/issues/342

### CODE REVIEW

**Comment by EmileSonneveld** [comment]
I used 40 seconds timeout, because that was already used in `ProcessApi.scala`

**Comment by bossie** [comment]
Might as well include this one too: https://github.com/Open-EO/openeo-geotrellis-extensions/blob/a8d79e045feab92b327f53a95adc8d93995c00be/geotrellis-sentinelhub/src/test/scala/org/openeo/geotrellissentinelhub/MemoizedCuratorCachedAccessTokenWithAuthApiFallbackAuthorizerTest.scala#L17

**Review by bossie — CHANGES_REQUESTED** [review]
Missed a call, otherwise fine.

**Review by bossie — APPROVED** [review]
Looks good.

**Pull request merged**
